### ISSUE TITLE
dependency issue with gem 'net-http-spy'

### ISSUE THREAD

**Issue by oliver-xapix-io** [iata-ndc/ndc-ruby-sdk#3]
I had to load `gem 'net-http-spy'` in my Gemfile to make it work. Might be a Rails specific topic, could you please check on that?

**Comment by xurde** [comment]
Fixed in f726f6d1724039b8bba278d81dc790358ba5bf7c.

**Comment by oliver-xapix-io** [comment]
thx. updated gem, works fine
